import assert from "node:assert/strict";
import { test } from "node:test";
import { standardizePosition } from "../app/lib/position-format.mjs";

const CASES = [
  ["CEO", "Chief Executive Officer"],
  ["CEO & Chairman", "Chief Executive Officer and Chairman"],
  ["co-CEO", "Co-Chief Executive Officer"],
  ["CFO & VP", "Chief Financial Officer and Vice President"],
  ["interim CFO & VP", "Interim Chief Financial Officer and Vice President"],
  ["MP", "Member of Parliament"],
  ["Eswatini PM", "Eswatini Prime Minister"],
  ["Former PM of Somalia", "Former Prime Minister of Somalia"],
  ["Essex GP", "Essex General Practitioner"],
  ["NYC Lawmaker", "New York City Lawmaker"],
  ["Ambassador to UN", "Ambassador to the United Nations"],
  ["FBI Director", "Federal Bureau of Investigation Director"],
  ["Former CIA Director", "Former Central Intelligence Agency Director"],
  ["(R) Ga", "(R), Georgia"],
  ["(R) Ala.", "(R), Alabama"],
  ["(D) MASS", "(D), Massachusetts"],
  ["(D) CALIFORNIA", "(D), California"],
  ["(D)-Washington", "(D), Washington"],
  ["(D-NY)", "(D), New York"],
  ["R-Florida", "(R), Florida"],
  ["(R) S.C.", "(R), South Carolina"],
  ["(R) N.D", "(R), North Dakota"],
  ["(R) Florida", "(R), Florida"],
  ["(D) Virginia Govenor", "Governor (D), Virginia"],
  ["(D) PA Govenor", "Governor (D), Pennsylvania"],
  [
    "(R) Ohio Govenor (Positive then later that day negative.",
    "Governor (R), Ohio (Positive then later that day negative.)",
  ],
  ["(R) Pennsylvania Congressman", "U.S. Representative (R), Pennsylvania"],
  ["(D) Rep from LA", "U.S. Representative (D), Louisiana"],
  [
    "(D) Rep from WI, went to congress 6 days after",
    "U.S. Representative (D), Wisconsin, went to congress 6 days after",
  ],
  ["(D) Rep from Washington state", "U.S. Representative (D), Washington"],
  ["House of Rep (D) Utah", "U.S. Representative (D), Utah"],
  ["House of Rep (R) from Florida", "U.S. Representative (R), Florida"],
  ["US REP (D) SC", "U.S. Representative (D), South Carolina"],
  ["(R) congressman elect LA", "U.S. Representative-elect (R), Louisiana"],
  ["Congressman", "U.S. Representative"],
  ["Congress Member", "U.S. Representative"],
  ["Representative", "U.S. Representative"],
  ["U.S. representative", "U.S. Representative"],
  ["U.S. senator", "U.S. Senator"],
  ["(R) US Senator Louisiana", "U.S. Senator (R), Louisiana"],
  ["US Senator from KY", "U.S. Senator from Kentucky"],
  ["(D) Penn senator", "Senator (D), Pennsylvania"],
  ["(D) Va Senator", "Senator (D), Virginia"],
  ["(R) Iowa Senator", "Senator (R), Iowa"],
  ["(R) Fla Senator", "Senator (R), Florida"],
  ["(R) Minnesota state Senator", "State Senator (R), Minnesota"],
  ["(R) VA State Senator", "State Senator (R), Virginia"],
  ["(R) PA State Rep", "State Representative (R), Pennsylvania"],
  ["State Rep.", "State Representative"],
  ["Georgia State Senator", "State Senator, Georgia"],
  ["Georgia House Rep", "State Representative, Georgia"],
  ["North Carolina Senator", "Senator, North Carolina"],
  ["Democratic New York Rep", "U.S. Representative (D), New York"],
  ["(R) RNC Chair women", "Republican National Committee Chairwoman (R)"],
  ["U.S. Representative (R-IN)", "U.S. Representative (R), Indiana"],
  [
    "U.S. Representative (R-FL-17)",
    "U.S. Representative (R) from Florida's 17th Congressional District",
  ],
  ["U.S. Senator (D-CA)", "U.S. Senator (D), California"],
  [
    "U.S. Senator (D-IL); later 44th President of the United States",
    "U.S. Senator (D), Illinois; Later 44th President of the United States",
  ],
  ["Israel Government Offical", "Israel Government Official"],
  ["(D) Illinous", "(D), Illinois"],
  ["Chief of staff", "Chief of Staff"],
  ["Country singer", "Country Singer"],
  ["singer", "Singer"],
  ["actress", "Actress"],
  ["Actor", "Actor"],
  ["Actress", "Actress"],
  ["President", "President"],
  ["Senator", "Senator"],
  ["Secretary of State", "Secretary of State"],
  ["Director", "Director"],
  ["Former President of the United States", "Former President of the United States"],
  ["44th President of the United States", "44th President of the United States"],
  ["President of the United States (45th/47th)", "President of the United States (45th/47th)"],
  [
    "President of the United States (45th/47th); defendant People v. Trump (NY County)",
    "President of the United States (45th/47th)",
  ],
  [
    "Vice Chairman of the Central Military Commission; Member of the Political Bureau of the CPC Central Committee",
    "Vice Chairman of the Central Military Commission; Member of the Political Bureau of the Communist Party of China Central Committee",
  ],
  ["President: On Oct 1st (Red October)", "President: On October 1st (Red October)"],
  ["POTUS Son.  Positive then Negative.", "Son of the President of the United States. Positive then Negative."],
  ["Rep. Ilhan Omar's father", "Representative Ilhan Omar's father"],
  ["Rep. Carolyn Maloney's (D-N.Y.) primary challenger", "Representative Carolyn Maloney's (D), New York primary challenger"],
  ["Chairman of N.M. Rothschild & Sons", "Chairman of N.M. Rothschild and Sons"],
  ["CFO Jefferies Financial Group Inc.", "Chief Financial Officer Jefferies Financial Group Incorporated"],
  ["Chairman, Xerox Corp.", "Chairman, Xerox Corporation"],
  ["Minnesota Lt. Govenors's Brother", "Minnesota Lieutenant Governor's Brother"],
  ["former bank employee", "Former bank employee"],
  ["former colonel", "Former Colonel"],
  ["global ambassador", "Global Ambassador"],
  ["staff secretary", "Staff Secretary"],
  ["Texas judge dies days before runoff election", "Texas judge dies days before runoff election"],
  ["Pence's press secretary", "Pence's press secretary"],
  ["British Health minister", "British Health Minister"],
  ["Actress star of 'Frozen2", "Actress star of Frozen2"],
  ["singer-songwriter-guitarist", "Singer-songwriter-guitarist"],
  ["wife of John Huntsman, Ambassador USA to Russia", "Wife of John Huntsman, U.S. Ambassador to Russia"],
  ["Chairman Council of Economic Advisers", "Chairman, Council of Economic Advisors"],
  ["Chiropractor", "Chiropractor"],
  ["Tight end and head coach", "Tight end and head coach"],
  ["", ""],
  ["   ", ""],
];

test("position titles use one spelling and spell out abbreviations", () => {
  for (const [input, output] of CASES) {
    assert.equal(standardizePosition(input), output, input);
    assert.equal(standardizePosition(output), output, `idempotent ${input}`);
  }
});
